# Generated by Django 6.1 on 2026-08-18

import django.db.models.deletion
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("prices", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(max_length=40)),
                ("unit", models.CharField(default="toman", max_length=12)),
                ("prices", models.JSONField(default=dict)),
                ("changes", models.JSONField(default=dict)),
                ("provider_timestamp", models.DateTimeField(blank=True, null=True)),
                (
                    "captured_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                    ),
                ),
            ],
            options={"ordering": ("-captured_at",)},
        ),
    ]
