"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path
from urllib.parse import parse_qs, unquote, urlparse

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

try:
    from dotenv import load_dotenv
except ImportError:  # The production build installs python-dotenv from requirements.txt.
    load_dotenv = None

if load_dotenv:
    load_dotenv(BASE_DIR / ".env")


def _env_text(name, default=""):
    """Read an environment value while treating empty dashboard fields as unset."""
    value = os.getenv(name)
    return value.strip() if value and value.strip() else default


def _env_int(name, default, minimum=None):
    """Parse deployment integers without letting an empty value break startup."""
    raw_value = os.getenv(name)
    try:
        value = int(raw_value.strip()) if raw_value and raw_value.strip() else int(default)
    except (TypeError, ValueError):
        value = int(default)
    return max(minimum, value) if minimum is not None else value


def _postgres_database(url):
    """Convert a Neon PostgreSQL URL into Django's database configuration."""
    parsed = urlparse(url)
    if parsed.scheme not in {"postgres", "postgresql"} or not parsed.hostname:
        raise ValueError("DATABASE_URL must be a valid PostgreSQL connection URL")

    query = parse_qs(parsed.query)
    options = {key: values[-1] for key, values in query.items() if values}
    options.setdefault("sslmode", "require")
    return {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": unquote(parsed.path.lstrip("/")),
        "USER": unquote(parsed.username or ""),
        "PASSWORD": unquote(parsed.password or ""),
        "HOST": parsed.hostname,
        "PORT": str(parsed.port or 5432),
        "OPTIONS": options,
        # A serverless function should release connections after each request;
        # the local worker can reuse one briefly for better efficiency.
        "CONN_MAX_AGE": 0 if _env_text("VERCEL") else 60,
        "CONN_HEALTH_CHECKS": True,
    }


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = _env_text(
    "SECRET_KEY",
    'rahmani-local-fallback-key-change-this-in-vercel-7f3e9d1c5a8b4e2f6d0c9b7a1e5f3d8',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _env_text("DEBUG", "False" if _env_text("VERCEL") else "True").lower() in {
    "1",
    "true",
    "yes",
    "on",
}

_allowed_hosts = _env_text("ALLOWED_HOSTS", "127.0.0.1,localhost,.vercel.app").split(",")
for _deployment_host_var in ("VERCEL_URL", "VERCEL_BRANCH_URL", "VERCEL_PROJECT_PRODUCTION_URL"):
    _deployment_host = _env_text(_deployment_host_var)
    if _deployment_host:
        _allowed_hosts.append(_deployment_host)
ALLOWED_HOSTS = list(dict.fromkeys(host.strip() for host in _allowed_hosts if host.strip()))


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'prices',
    'rest_framework',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASE_URL = _env_text("DATABASE_URL")
if DATABASE_URL:
    DATABASES = {"default": _postgres_database(DATABASE_URL)}
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Tehran'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'


# Market provider configuration. Keep credentials in the environment, never in frontend code.
MARKET_PROVIDER = _env_text("MARKET_PROVIDER", "tgju_scrape").lower()
MARKET_PROVIDER_URL = _env_text("MARKET_PROVIDER_URL")
MARKET_PROVIDER_TOKEN = _env_text("MARKET_PROVIDER_TOKEN")
_default_market_provider_items = (
    "usd,eur,geram18,geram24,silver_999,crypto-tether,sekeb,nim,rob,ons,energy-brent-oil"
)
_configured_market_items = _env_text("MARKET_PROVIDER_ITEMS")
MARKET_PROVIDER_ITEMS = ",".join(
    dict.fromkeys(
        item.strip()
        for item in f"{_configured_market_items},{_default_market_provider_items}".split(",")
        if item.strip()
    )
)
MARKET_PROVIDER_UNIT = _env_text("MARKET_PROVIDER_UNIT", "rial").lower()
MARKET_DISPLAY_UNIT = _env_text("MARKET_DISPLAY_UNIT", "toman").lower()
MARKET_PRICE_CACHE_SECONDS = _env_int("MARKET_PRICE_CACHE_SECONDS", 5, minimum=0)
MARKET_PROVIDER_TIMEOUT_SECONDS = _env_int("MARKET_PROVIDER_TIMEOUT_SECONDS", 8, minimum=1)
MARKET_UPDATE_INTERVAL_SECONDS = _env_int("MARKET_UPDATE_INTERVAL_SECONDS", 5, minimum=1)
MARKET_SNAPSHOT_STALE_AFTER_SECONDS = _env_int(
    "MARKET_SNAPSHOT_STALE_AFTER_SECONDS",
    10 if _env_text("VERCEL") else 30,
    minimum=1,
)
TGJU_SCRAPE_URL = _env_text("TGJU_SCRAPE_URL", "https://www.tgju.org/home")
TGJU_SCRAPE_GOLD_URL = _env_text("TGJU_SCRAPE_GOLD_URL", "https://www.tgju.org/gold-chart")
TGJU_PROFILE_BASE_URL = _env_text("TGJU_PROFILE_BASE_URL", "https://www.tgju.org/profile")
TGJU_PROFILE_URL = _env_text("TGJU_PROFILE_URL", "https://www.tgju.org/profile/geram18")
TGJU_LOCAL_MARKETS_URL = _env_text("TGJU_LOCAL_MARKETS_URL", "https://www.tgju.org/local-markets")
TGJU_GLOBAL_MARKETS_URL = _env_text(
    "TGJU_GLOBAL_MARKETS_URL",
    "https://www.tgju.org/profile/crypto-page/markets-global",
)
TGJU_MARKET_LIST_API_URL = _env_text(
    "TGJU_MARKET_LIST_API_URL",
    "https://api.tgju.org/v1/market/list-data",
)
TGJU_GOLD_CATEGORY_ID = _env_text("TGJU_GOLD_CATEGORY_ID", "91818")
TGJU_CURRENCY_CATEGORY_ID = _env_text("TGJU_CURRENCY_CATEGORY_ID", "28070")
TGJU_HISTORY_API_URL = _env_text(
    "TGJU_HISTORY_API_URL",
    "https://api.tgju.org/v1/market/indicator/summary-table-data/geram18",
)
TGJU_HISTORY_PAGE_LENGTH = _env_int("TGJU_HISTORY_PAGE_LENGTH", 5000, minimum=7)


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': _env_text(
            "EMAIL_BACKEND",
            "django.core.mail.backends.smtp.EmailBackend"
            if not DEBUG
            else "django.core.mail.backends.console.EmailBackend",
        ),
    },
}

if not DEBUG:
    # Vercel terminates HTTPS before the Django function; do not redirect again.
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
