"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-427=s70n(+i%#=9*5#)1)t8q0%xhv7z+ob&myvylo7+xiu+1&9'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [host.strip() for host in os.getenv("ALLOWED_HOSTS", "127.0.0.1,localhost").split(",") if host.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'prices',
    'rest_framework',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Tehran'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'


# Market provider configuration. Keep credentials in the environment, never in frontend code.
MARKET_PROVIDER = os.getenv("MARKET_PROVIDER", "tgju_scrape").lower()
MARKET_PROVIDER_URL = os.getenv("MARKET_PROVIDER_URL", "")
MARKET_PROVIDER_TOKEN = os.getenv("MARKET_PROVIDER_TOKEN", "")
MARKET_PROVIDER_ITEMS = os.getenv("MARKET_PROVIDER_ITEMS", "usd,eur,geram18,geram24,silver_999")
MARKET_PROVIDER_UNIT = os.getenv("MARKET_PROVIDER_UNIT", "rial").lower()
MARKET_DISPLAY_UNIT = os.getenv("MARKET_DISPLAY_UNIT", "toman").lower()
MARKET_PRICE_CACHE_SECONDS = int(os.getenv("MARKET_PRICE_CACHE_SECONDS") or "10")
MARKET_PROVIDER_TIMEOUT_SECONDS = int(os.getenv("MARKET_PROVIDER_TIMEOUT_SECONDS", "8"))
MARKET_UPDATE_INTERVAL_SECONDS = int(os.getenv("MARKET_UPDATE_INTERVAL_SECONDS", "10"))
MARKET_SNAPSHOT_STALE_AFTER_SECONDS = int(os.getenv("MARKET_SNAPSHOT_STALE_AFTER_SECONDS", "30"))
TGJU_SCRAPE_URL = os.getenv("TGJU_SCRAPE_URL", "https://www.tgju.org/home")
TGJU_SCRAPE_GOLD_URL = os.getenv("TGJU_SCRAPE_GOLD_URL", "https://www.tgju.org/gold-chart")
TGJU_PROFILE_BASE_URL = os.getenv("TGJU_PROFILE_BASE_URL", "https://www.tgju.org/profile")
TGJU_PROFILE_URL = os.getenv("TGJU_PROFILE_URL", "https://www.tgju.org/profile/geram18")
TGJU_MARKET_LIST_API_URL = os.getenv(
    "TGJU_MARKET_LIST_API_URL",
    "https://api.tgju.org/v1/market/list-data",
)
TGJU_GOLD_CATEGORY_ID = os.getenv("TGJU_GOLD_CATEGORY_ID", "91818")
TGJU_CURRENCY_CATEGORY_ID = os.getenv("TGJU_CURRENCY_CATEGORY_ID", "28070")
TGJU_HISTORY_API_URL = os.getenv(
    "TGJU_HISTORY_API_URL",
    "https://api.tgju.org/v1/market/indicator/summary-table-data/geram18",
)
TGJU_HISTORY_PAGE_LENGTH = int(os.getenv("TGJU_HISTORY_PAGE_LENGTH", "5000"))


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}
